# Generated by Django 2.2.3 on 2019-07-15 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planos', '0002_auto_20190715_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id_vendedor', models.AutoField(primary_key=True, serialize=False, verbose_name='Código vendedor')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone')),
                ('idade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Idade')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planos.PlanoComissoes', verbose_name='Plano de Comissão')),
            ],
            options={
                'verbose_name_plural': 'Vendedores',
                'ordering': ['nome'],
            },
        ),
    ]
