# Generated by Django 2.2.3 on 2019-07-15 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0003_auto_20190715_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='idade',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Idade'),
        ),
    ]
