# Generated by Django 2.2.3 on 2019-07-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoComissoes',
            fields=[
                ('id_plano', models.AutoField(primary_key=True, serialize=False, verbose_name='Código do plano')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor mínimo')),
                ('percent_min', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% mínimo')),
                ('percent_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% máximo')),
            ],
            options={
                'verbose_name': 'Plano de Comissão',
                'verbose_name_plural': 'Planos de Comissões',
                'ordering': ['descricao'],
            },
        ),
    ]
