# Generated by Django 2.2.3 on 2019-07-15 16:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planocomissoes',
            name='percent_max',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='% máximo'),
        ),
        migrations.AlterField(
            model_name='planocomissoes',
            name='percent_min',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='% mínimo'),
        ),
        migrations.AlterField(
            model_name='planocomissoes',
            name='valor_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Valor mínimo'),
        ),
    ]
